//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod timesheet_bulk;
pub mod timesheet_approval_bulk;

pub use timesheet_bulk::TimesheetBulkService;
pub use timesheet_approval_bulk::TimesheetApprovalBulkService;

// <<< CUSTOM
// END CUSTOM
