//! Bulk operation shared types — re-exported from backbone-core.
//!
//! Generated by metaphor-schema. Do not edit manually.

pub use backbone_core::{
    BulkOperationConfig, BulkFailureMode,
    BulkItemResult, BulkOperationResult,
    BulkOperationProgress, BulkCapableService, GenericBulkService,
};
