//! Bulk operations for TimesheetApproval entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTimesheetApprovalDto;
use crate::application::service::TimesheetApprovalService;
use crate::domain::entity::TimesheetApproval;

/// Bulk operation handler for TimesheetApproval entities.
///
/// Wraps `TimesheetApprovalService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TimesheetApprovalBulkService = GenericBulkService<TimesheetApproval, CreateTimesheetApprovalDto, TimesheetApprovalService>;

// <<< CUSTOM
// END CUSTOM
