//! Bulk operations for Timesheet entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTimesheetDto;
use crate::application::service::TimesheetService;
use crate::domain::entity::Timesheet;

/// Bulk operation handler for Timesheet entities.
///
/// Wraps `TimesheetService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TimesheetBulkService = GenericBulkService<Timesheet, CreateTimesheetDto, TimesheetService>;

// <<< CUSTOM
// END CUSTOM
