//! RateCard DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::RateCard;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new RateCard
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateRateCardDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "activity_type_id")]
    pub activity_type_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "billing_rate")]
    pub billing_rate: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "costing_rate")]
    pub costing_rate: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "valid_from")]
    pub valid_from: NaiveDate,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a RateCard
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateRateCardDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "activity_type_id")]
    pub activity_type_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "billing_rate")]
    pub billing_rate: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "costing_rate")]
    pub costing_rate: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "valid_from")]
    pub valid_from: NaiveDate,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a RateCard
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchRateCardDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "activity_type_id")]
    pub activity_type_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "billing_rate")]
    pub billing_rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "costing_rate")]
    pub costing_rate: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "valid_from")]
    pub valid_from: Option<NaiveDate>,
}

impl PatchRateCardDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.employee_id.is_some() || self.activity_type_id.is_some() || self.billing_rate.is_some() || self.costing_rate.is_some() || self.valid_from.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for RateCard entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RateCardResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub activity_type_id: Option<Uuid>,
    pub billing_rate: Option<Decimal>,
    pub costing_rate: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub valid_from: NaiveDate,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for RateCard entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RateCardListResponseDto {
    /// List of items
    pub items: Vec<RateCardResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl RateCardListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<RateCardResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct RateCardSummaryDto {
    pub id: Uuid,
    pub employee_id: Uuid,
    pub activity_type_id: Option<Uuid>,
    pub billing_rate: Option<Decimal>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<RateCard> for RateCardResponseDto {
    fn from(entity: RateCard) -> Self {
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            activity_type_id: entity.activity_type_id,
            billing_rate: entity.billing_rate,
            costing_rate: entity.costing_rate,
            valid_from: entity.valid_from,
            metadata: entity.metadata,
        }
    }
}

impl From<RateCard> for RateCardSummaryDto {
    fn from(entity: RateCard) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            activity_type_id: entity.activity_type_id,
            billing_rate: entity.billing_rate,
            created_at,
        }
    }
}

impl From<CreateRateCardDto> for RateCard {
    fn from(dto: CreateRateCardDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            employee_id: dto.employee_id,
            activity_type_id: dto.activity_type_id,
            billing_rate: dto.billing_rate,
            costing_rate: dto.costing_rate,
            valid_from: dto.valid_from,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&RateCard> for RateCardResponseDto {
    fn from(entity: &RateCard) -> Self {
        Self {
            id: entity.id.clone(),
            employee_id: entity.employee_id.clone(),
            activity_type_id: entity.activity_type_id.clone(),
            billing_rate: entity.billing_rate.clone(),
            costing_rate: entity.costing_rate.clone(),
            valid_from: entity.valid_from.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateRateCardDto> for RateCard {
    fn from_create_dto(dto: CreateRateCardDto) -> backbone_core::ServiceResult<Self> {
        Ok(RateCard::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateRateCardDto> for RateCard {
    fn apply_update(mut self, dto: UpdateRateCardDto) -> backbone_core::ServiceResult<Self> {
        self.employee_id = dto.employee_id;
        self.activity_type_id = dto.activity_type_id;
        self.billing_rate = dto.billing_rate;
        self.costing_rate = dto.costing_rate;
        self.valid_from = dto.valid_from;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to RateCard here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

