//! TimesheetApproval DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::TimesheetApproval;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::TimesheetApprovalStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TimesheetApproval
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTimesheetApprovalDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approver_id")]
    pub approver_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub year: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub month: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remark: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "billable_time")]
    pub billable_time: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "billable_cost")]
    pub billable_cost: Option<Decimal>,
    pub status: TimesheetApprovalStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TimesheetApproval
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTimesheetApprovalDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approver_id")]
    pub approver_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub year: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub month: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remark: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "billable_time")]
    pub billable_time: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "billable_cost")]
    pub billable_cost: Option<Decimal>,
    pub status: TimesheetApprovalStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TimesheetApproval
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTimesheetApprovalDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approver_id")]
    pub approver_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub year: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub month: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "billable_time")]
    pub billable_time: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "billable_cost")]
    pub billable_cost: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<TimesheetApprovalStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl PatchTimesheetApprovalDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.approver_id.is_some() || self.year.is_some() || self.month.is_some() || self.remark.is_some() || self.billable_time.is_some() || self.billable_cost.is_some() || self.status.is_some() || self.data.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TimesheetApproval entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimesheetApprovalResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub approver_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub year: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub month: i32,
    pub remark: Option<String>,
    pub billable_time: Option<Decimal>,
    pub billable_cost: Option<Decimal>,
    pub status: TimesheetApprovalStatus,
    pub data: Option<serde_json::Value>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TimesheetApproval entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimesheetApprovalListResponseDto {
    /// List of items
    pub items: Vec<TimesheetApprovalResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TimesheetApprovalListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TimesheetApprovalResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimesheetApprovalSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub approver_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TimesheetApproval> for TimesheetApprovalResponseDto {
    fn from(entity: TimesheetApproval) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            approver_id: entity.approver_id,
            year: entity.year,
            month: entity.month,
            remark: entity.remark,
            billable_time: entity.billable_time,
            billable_cost: entity.billable_cost,
            status: entity.status,
            data: entity.data,
            metadata: entity.metadata,
        }
    }
}

impl From<TimesheetApproval> for TimesheetApprovalSummaryDto {
    fn from(entity: TimesheetApproval) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            approver_id: entity.approver_id,
            created_at,
        }
    }
}

impl From<CreateTimesheetApprovalDto> for TimesheetApproval {
    fn from(dto: CreateTimesheetApprovalDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            approver_id: dto.approver_id,
            year: dto.year,
            month: dto.month,
            remark: dto.remark,
            billable_time: dto.billable_time,
            billable_cost: dto.billable_cost,
            status: dto.status,
            data: dto.data,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TimesheetApproval> for TimesheetApprovalResponseDto {
    fn from(entity: &TimesheetApproval) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            approver_id: entity.approver_id.clone(),
            year: entity.year.clone(),
            month: entity.month.clone(),
            remark: entity.remark.clone(),
            billable_time: entity.billable_time.clone(),
            billable_cost: entity.billable_cost.clone(),
            status: entity.status.clone(),
            data: entity.data.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTimesheetApprovalDto> for TimesheetApproval {
    fn from_create_dto(dto: CreateTimesheetApprovalDto) -> backbone_core::ServiceResult<Self> {
        Ok(TimesheetApproval::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTimesheetApprovalDto> for TimesheetApproval {
    fn apply_update(mut self, dto: UpdateTimesheetApprovalDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.approver_id = dto.approver_id;
        self.year = dto.year;
        self.month = dto.month;
        self.remark = dto.remark;
        self.billable_time = dto.billable_time;
        self.billable_cost = dto.billable_cost;
        self.status = dto.status;
        self.data = dto.data;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TimesheetApproval here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

