//! Timesheet DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Timesheet;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::TimesheetType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Timesheet
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTimesheetDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "project_id")]
    pub project_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "task_id")]
    pub task_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub year: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub month: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remark: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "time_start")]
    pub time_start: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "time_end")]
    pub time_end: Option<DateTime<Utc>>,
    #[serde(alias = "entry_type")]
    pub entry_type: TimesheetType,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Timesheet
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTimesheetDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "project_id")]
    pub project_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "task_id")]
    pub task_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub year: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub month: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remark: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "time_start")]
    pub time_start: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "time_end")]
    pub time_end: Option<DateTime<Utc>>,
    #[serde(alias = "entry_type")]
    pub entry_type: TimesheetType,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Timesheet
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTimesheetDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "project_id")]
    pub project_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "task_id")]
    pub task_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub year: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub month: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remark: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "time_start")]
    pub time_start: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "time_end")]
    pub time_end: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "entry_type")]
    pub entry_type: Option<TimesheetType>,
}

impl PatchTimesheetDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.project_id.is_some() || self.task_id.is_some() || self.year.is_some() || self.month.is_some() || self.date.is_some() || self.remark.is_some() || self.time_start.is_some() || self.time_end.is_some() || self.entry_type.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Timesheet entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimesheetResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub project_id: Option<Uuid>,
    pub task_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub year: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub month: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    pub remark: Option<String>,
    pub time_start: Option<DateTime<Utc>>,
    pub time_end: Option<DateTime<Utc>>,
    pub entry_type: TimesheetType,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Timesheet entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimesheetListResponseDto {
    /// List of items
    pub items: Vec<TimesheetResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TimesheetListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TimesheetResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TimesheetSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub project_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Timesheet> for TimesheetResponseDto {
    fn from(entity: Timesheet) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            project_id: entity.project_id,
            task_id: entity.task_id,
            year: entity.year,
            month: entity.month,
            date: entity.date,
            remark: entity.remark,
            time_start: entity.time_start,
            time_end: entity.time_end,
            entry_type: entity.entry_type,
            metadata: entity.metadata,
        }
    }
}

impl From<Timesheet> for TimesheetSummaryDto {
    fn from(entity: Timesheet) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            project_id: entity.project_id,
            created_at,
        }
    }
}

impl From<CreateTimesheetDto> for Timesheet {
    fn from(dto: CreateTimesheetDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            project_id: dto.project_id,
            task_id: dto.task_id,
            year: dto.year,
            month: dto.month,
            date: dto.date,
            remark: dto.remark,
            time_start: dto.time_start,
            time_end: dto.time_end,
            entry_type: dto.entry_type,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Timesheet> for TimesheetResponseDto {
    fn from(entity: &Timesheet) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            project_id: entity.project_id.clone(),
            task_id: entity.task_id.clone(),
            year: entity.year.clone(),
            month: entity.month.clone(),
            date: entity.date.clone(),
            remark: entity.remark.clone(),
            time_start: entity.time_start.clone(),
            time_end: entity.time_end.clone(),
            entry_type: entity.entry_type.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTimesheetDto> for Timesheet {
    fn from_create_dto(dto: CreateTimesheetDto) -> backbone_core::ServiceResult<Self> {
        Ok(Timesheet::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTimesheetDto> for Timesheet {
    fn apply_update(mut self, dto: UpdateTimesheetDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.project_id = dto.project_id;
        self.task_id = dto.task_id;
        self.year = dto.year;
        self.month = dto.month;
        self.date = dto.date;
        self.remark = dto.remark;
        self.time_start = dto.time_start;
        self.time_end = dto.time_end;
        self.entry_type = dto.entry_type;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Timesheet here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

