//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod timesheet_domain_policy;
pub mod timesheet_approval_domain_policy;

pub use timesheet_domain_policy::TimesheetDomainPolicy;
pub use timesheet_approval_domain_policy::TimesheetApprovalDomainPolicy;

// <<< CUSTOM
// END CUSTOM
