//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod timesheet_service;
pub mod timesheet_approval_service;

// <<< CUSTOM
// END CUSTOM

pub use timesheet_service::TimesheetService;
pub use timesheet_approval_service::TimesheetApprovalService;
// <<< CUSTOM
// END CUSTOM
