//! Application service for RateCard entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `rate_card_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateRateCardDto, UpdateRateCardDto};
use crate::domain::entity::RateCard;
use crate::infrastructure::persistence::RateCardRepository;

/// Application service for RateCard entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `rate_card_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct RateCardServiceCustom {
///     inner: Arc<RateCardService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type RateCardService = GenericCrudService<
    RateCard,
    CreateRateCardDto,
    UpdateRateCardDto,
    RateCardRepository,
>;

// <<< CUSTOM
// END CUSTOM
