//! Application service for Timesheet entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `timesheet_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTimesheetDto, UpdateTimesheetDto};
use crate::domain::entity::Timesheet;
use crate::infrastructure::persistence::TimesheetRepository;

/// Application service for Timesheet entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `timesheet_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TimesheetServiceCustom {
///     inner: Arc<TimesheetService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TimesheetService = GenericCrudService<
    Timesheet,
    CreateTimesheetDto,
    UpdateTimesheetDto,
    TimesheetRepository,
>;

// <<< CUSTOM
// END CUSTOM
