//! Application service for TimesheetApproval entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `timesheet_approval_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTimesheetApprovalDto, UpdateTimesheetApprovalDto};
use crate::domain::entity::TimesheetApproval;
use crate::infrastructure::persistence::TimesheetApprovalRepository;

/// Application service for TimesheetApproval entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `timesheet_approval_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TimesheetApprovalServiceCustom {
///     inner: Arc<TimesheetApprovalService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TimesheetApprovalService = GenericCrudService<
    TimesheetApproval,
    CreateTimesheetApprovalDto,
    UpdateTimesheetApprovalDto,
    TimesheetApprovalRepository,
>;

// <<< CUSTOM
// END CUSTOM
