-- RateCard Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the timesheet.rate_cards table.
-- Customize this file to add your initial data.

-- INSERT INTO timesheet.rate_cards (
--     id,
--     employee_id,
--     activity_type_id,
--     billing_rate,
--     costing_rate,
--     valid_from,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO timesheet.rate_cards (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

