-- TimesheetApproval Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the timesheet.timesheet_approvals table.
-- Customize this file to add your initial data.

-- INSERT INTO timesheet.timesheet_approvals (
--     id,
--     company_id,
--     employee_id,
--     approver_id,
--     year,
--     month,
--     remark,
--     billable_time,
--     billable_cost,
--     status,
--     data,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO timesheet.timesheet_approvals (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

