-- Timesheet Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the timesheet.timesheets table.
-- Customize this file to add your initial data.

-- INSERT INTO timesheet.timesheets (
--     id,
--     company_id,
--     employee_id,
--     project_id,
--     task_id,
--     year,
--     month,
--     date,
--     remark,
--     time_start,
--     time_end,
--     type,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO timesheet.timesheets (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

