-- Migration: Create rate_cards table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS timesheet;

CREATE TABLE IF NOT EXISTS timesheet.rate_cards (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    employee_id UUID NOT NULL,
    activity_type_id UUID,
    billing_rate NUMERIC(18, 4),
    costing_rate NUMERIC(18, 4),
    valid_from DATE NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_rate_cards_employee_id_valid_from ON timesheet.rate_cards (employee_id, valid_from);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_rate_cards_metadata_gin ON timesheet.rate_cards USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_rate_cards_metadata_deleted_at ON timesheet.rate_cards ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_rate_cards_metadata_created_at ON timesheet.rate_cards ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_rate_cards_metadata_updated_at ON timesheet.rate_cards ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION timesheet.rate_cards_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS rate_cards_insert_audit ON timesheet.rate_cards;
CREATE TRIGGER rate_cards_insert_audit BEFORE INSERT ON timesheet.rate_cards
    FOR EACH ROW EXECUTE FUNCTION timesheet.rate_cards_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS rate_cards_update_audit ON timesheet.rate_cards;
CREATE TRIGGER rate_cards_update_audit BEFORE UPDATE ON timesheet.rate_cards
    FOR EACH ROW EXECUTE FUNCTION timesheet.rate_cards_audit_timestamp();
