-- Migration: Create timesheets table
-- Generated by metaphor-schema

-- Create timesheet_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'timesheet_type') THEN
        CREATE TYPE timesheet_type AS ENUM ('work', 'overtime');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS timesheet;

CREATE TABLE IF NOT EXISTS timesheet.timesheets (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    project_id UUID,
    task_id UUID,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    date DATE NOT NULL,
    remark TEXT,
    time_start TIMESTAMPTZ,
    time_end TIMESTAMPTZ,
    type timesheet_type NOT NULL DEFAULT 'work',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_timesheets_company_id_employee_id_date ON timesheet.timesheets (company_id, employee_id, date);

CREATE INDEX IF NOT EXISTS idx_timesheets_project_id ON timesheet.timesheets (project_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_timesheets_metadata_gin ON timesheet.timesheets USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_timesheets_metadata_deleted_at ON timesheet.timesheets ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_timesheets_metadata_created_at ON timesheet.timesheets ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_timesheets_metadata_updated_at ON timesheet.timesheets ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION timesheet.timesheets_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS timesheets_insert_audit ON timesheet.timesheets;
CREATE TRIGGER timesheets_insert_audit BEFORE INSERT ON timesheet.timesheets
    FOR EACH ROW EXECUTE FUNCTION timesheet.timesheets_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS timesheets_update_audit ON timesheet.timesheets;
CREATE TRIGGER timesheets_update_audit BEFORE UPDATE ON timesheet.timesheets
    FOR EACH ROW EXECUTE FUNCTION timesheet.timesheets_audit_timestamp();
