-- Revert the ADR-0014 strict company fence for timesheet module (Wave 1 P0 sweep).
-- Generated by metaphor-schema.
DROP POLICY IF EXISTS timesheet_approvals_company_isolation ON timesheet.timesheet_approvals;
ALTER TABLE timesheet.timesheet_approvals NO FORCE ROW LEVEL SECURITY;
ALTER TABLE timesheet.timesheet_approvals DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS timesheets_company_isolation ON timesheet.timesheets;
ALTER TABLE timesheet.timesheets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE timesheet.timesheets DISABLE ROW LEVEL SECURITY;
