-- Audit Triggers Migration for timesheet module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Timesheet (timesheet.timesheets)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION timesheet.timesheets_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS timesheets_insert_audit ON timesheet.timesheets;
CREATE TRIGGER timesheets_insert_audit BEFORE INSERT ON timesheet.timesheets
    FOR EACH ROW EXECUTE FUNCTION timesheet.timesheets_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS timesheets_update_audit ON timesheet.timesheets;
CREATE TRIGGER timesheets_update_audit BEFORE UPDATE ON timesheet.timesheets
    FOR EACH ROW EXECUTE FUNCTION timesheet.timesheets_audit_timestamp();

-- ==============================================================================
-- Table: TimesheetApproval (timesheet.timesheet_approvals)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION timesheet.timesheet_approvals_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS timesheet_approvals_insert_audit ON timesheet.timesheet_approvals;
CREATE TRIGGER timesheet_approvals_insert_audit BEFORE INSERT ON timesheet.timesheet_approvals
    FOR EACH ROW EXECUTE FUNCTION timesheet.timesheet_approvals_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS timesheet_approvals_update_audit ON timesheet.timesheet_approvals;
CREATE TRIGGER timesheet_approvals_update_audit BEFORE UPDATE ON timesheet.timesheet_approvals
    FOR EACH ROW EXECUTE FUNCTION timesheet.timesheet_approvals_audit_timestamp();

