-- Migration: Create timesheet_approvals table
-- Generated by metaphor-schema

-- Create timesheet_approval_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'timesheet_approval_status') THEN
        CREATE TYPE timesheet_approval_status AS ENUM ('pending', 'approved', 'rejected');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS timesheet;

CREATE TABLE IF NOT EXISTS timesheet.timesheet_approvals (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    approver_id UUID,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    remark TEXT,
    billable_time NUMERIC(18, 2),
    billable_cost NUMERIC(12, 2),
    status timesheet_approval_status NOT NULL DEFAULT 'pending',
    data JSONB,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_timesheet_approvals_company_id_employee_id_year_month ON timesheet.timesheet_approvals (company_id, employee_id, year, month);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_timesheet_approvals_metadata_gin ON timesheet.timesheet_approvals USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_timesheet_approvals_metadata_deleted_at ON timesheet.timesheet_approvals ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_timesheet_approvals_metadata_created_at ON timesheet.timesheet_approvals ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_timesheet_approvals_metadata_updated_at ON timesheet.timesheet_approvals ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION timesheet.timesheet_approvals_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS timesheet_approvals_insert_audit ON timesheet.timesheet_approvals;
CREATE TRIGGER timesheet_approvals_insert_audit BEFORE INSERT ON timesheet.timesheet_approvals
    FOR EACH ROW EXECUTE FUNCTION timesheet.timesheet_approvals_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS timesheet_approvals_update_audit ON timesheet.timesheet_approvals;
CREATE TRIGGER timesheet_approvals_update_audit BEFORE UPDATE ON timesheet.timesheet_approvals
    FOR EACH ROW EXECUTE FUNCTION timesheet.timesheet_approvals_audit_timestamp();
