-- Enum types for timesheet module
-- Generated by metaphor-schema

-- Create timesheet_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'timesheet_type') THEN
        CREATE TYPE timesheet_type AS ENUM ('work', 'overtime');
    END IF;
END
$$;

-- Create timesheet_approval_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'timesheet_approval_status') THEN
        CREATE TYPE timesheet_approval_status AS ENUM ('pending', 'approved', 'rejected');
    END IF;
END
$$;

