-- Company RLS fence for timesheet module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for timesheet.timesheets
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE timesheet.timesheets ENABLE ROW LEVEL SECURITY;
ALTER TABLE timesheet.timesheets FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS timesheets_company_isolation ON timesheet.timesheets;
CREATE POLICY timesheets_company_isolation ON timesheet.timesheets
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for timesheet.timesheet_approvals
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE timesheet.timesheet_approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE timesheet.timesheet_approvals FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS timesheet_approvals_company_isolation ON timesheet.timesheet_approvals;
CREATE POLICY timesheet_approvals_company_isolation ON timesheet.timesheet_approvals
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

