//! Event handler trait for RateCard events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::RateCardEvent;

/// Event handler for RateCard events.
/// Implement this trait to react to RateCard lifecycle events.
pub trait RateCardEventHandler: EventHandler<RateCardEvent> {}
