//! Domain events for RateCard entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::RateCard;

/// Domain events for RateCard — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<RateCard>)` variant.
pub type RateCardEvent = CrudEvent<RateCard>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for RateCard events.
pub type RateCardEventPublisher = Arc<dyn CrudEventPublisher<RateCard> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopRateCardEventPublisher = NoOpCrudEventPublisher<RateCard>;
