//! Domain events for TimesheetApproval entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::TimesheetApproval;

/// Domain events for TimesheetApproval — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TimesheetApproval>)` variant.
pub type TimesheetApprovalEvent = CrudEvent<TimesheetApproval>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TimesheetApproval events.
pub type TimesheetApprovalEventPublisher = Arc<dyn CrudEventPublisher<TimesheetApproval> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTimesheetApprovalEventPublisher = NoOpCrudEventPublisher<TimesheetApproval>;
