//! Domain events for Timesheet entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Timesheet;

/// Domain events for Timesheet — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Timesheet>)` variant.
pub type TimesheetEvent = CrudEvent<Timesheet>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Timesheet events.
pub type TimesheetEventPublisher = Arc<dyn CrudEventPublisher<Timesheet> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTimesheetEventPublisher = NoOpCrudEventPublisher<Timesheet>;
