//! Event handler trait for Timesheet events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TimesheetEvent;

/// Event handler for Timesheet events.
/// Implement this trait to react to Timesheet lifecycle events.
pub trait TimesheetEventHandler: EventHandler<TimesheetEvent> {}
