//! Event handler trait for TimesheetApproval events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TimesheetApprovalEvent;

/// Event handler for TimesheetApproval events.
/// Implement this trait to react to TimesheetApproval lifecycle events.
pub trait TimesheetApprovalEventHandler: EventHandler<TimesheetApprovalEvent> {}
