//! Common integration-test helpers.
//!
//! Generated by metaphor-schema. Do not edit manually.
#![allow(dead_code)]

/// Shared utilities handed to entity test-data generators. Generators accept this by
/// reference for forward-compatibility (seeded RNG, fixtures, …) even when unused today.
#[derive(Debug, Clone, Default)]
pub struct CommonUtils;
