//! TimesheetApproval seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial TimesheetApproval data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TIMESHEETAPPROVAL SEEDER
// ============================================================================

/// Seeder for timesheet_approval
pub struct SeedTimesheetApprovalSeeder;

impl SeedTimesheetApprovalSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTimesheetApprovalSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTimesheetApprovalSeeder {
    fn name(&self) -> &'static str {
        "SeedTimesheetApprovalSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if timesheet.timesheet_approvals table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM timesheet.timesheet_approvals")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/timesheet_approval_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM timesheet.timesheet_approvals")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

