//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod timesheet_repository;
pub mod timesheet_approval_repository;

// Re-exports
pub use timesheet_repository::{
    TimesheetRepository,
    TimesheetPaginationParams,
    TimesheetPaginatedResult,
    TimesheetFilter,
};
pub use timesheet_approval_repository::{
    TimesheetApprovalRepository,
    TimesheetApprovalPaginationParams,
    TimesheetApprovalPaginatedResult,
    TimesheetApprovalFilter,
};
