//! Repository trait for RateCard aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the RateCard aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::RateCard;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RateCardPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl RateCardPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct RateCardPaginatedResult {
    pub data: Vec<RateCard>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RateCardFilter {
    pub employee_id: Option<Uuid>,
    pub activity_type_id: Option<Uuid>,
}

impl RateCardFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.employee_id.is_some() || self.activity_type_id.is_some()
    }
}

/// Repository trait for RateCard aggregate
///
/// This trait defines the persistence contract for RateCard entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait RateCardRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new rate_card entity
    async fn save(&self, entity: &RateCard) -> Result<RateCard>;

    /// Find rate_card by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<RateCard>>;

    /// Find all rate_card entities
    async fn find_all(&self) -> Result<Vec<RateCard>>;

    /// Update rate_card by ID
    async fn update(&self, id: &str, entity: &RateCard) -> Result<Option<RateCard>>;

    /// Delete rate_card by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List rate_card with pagination
    async fn list(&self, params: RateCardPaginationParams) -> Result<RateCardPaginatedResult>;

    /// List rate_card with pagination and filters
    async fn list_with_filters(&self, params: RateCardPaginationParams, filters: RateCardFilter) -> Result<RateCardPaginatedResult>;

    /// Count all rate_card entities
    async fn count(&self) -> Result<u64>;

    /// Count rate_card entities matching filters
    async fn count_with_filters(&self, filters: RateCardFilter) -> Result<u64>;

    /// Check if rate_card exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete rate_card by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted rate_card by ID
    async fn restore(&self, id: &str) -> Result<Option<RateCard>>;

    /// List soft-deleted rate_card entities
    async fn list_deleted(&self, params: RateCardPaginationParams) -> Result<RateCardPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save rate_card entities
    async fn bulk_save(&self, entities: &[RateCard]) -> Result<Vec<RateCard>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
