//! Repository trait for TimesheetApproval aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TimesheetApproval aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{TimesheetApproval, TimesheetApprovalStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimesheetApprovalPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TimesheetApprovalPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TimesheetApprovalPaginatedResult {
    pub data: Vec<TimesheetApproval>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimesheetApprovalFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub approver_id: Option<Uuid>,
    pub remark: Option<String>,
    pub status: Option<TimesheetApprovalStatus>,
}

impl TimesheetApprovalFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.approver_id.is_some() || self.remark.is_some() || self.status.is_some()
    }
}

/// Repository trait for TimesheetApproval aggregate
///
/// This trait defines the persistence contract for TimesheetApproval entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TimesheetApprovalRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new timesheet_approval entity
    async fn save(&self, entity: &TimesheetApproval) -> Result<TimesheetApproval>;

    /// Find timesheet_approval by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TimesheetApproval>>;

    /// Find all timesheet_approval entities
    async fn find_all(&self) -> Result<Vec<TimesheetApproval>>;

    /// Update timesheet_approval by ID
    async fn update(&self, id: &str, entity: &TimesheetApproval) -> Result<Option<TimesheetApproval>>;

    /// Delete timesheet_approval by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List timesheet_approval with pagination
    async fn list(&self, params: TimesheetApprovalPaginationParams) -> Result<TimesheetApprovalPaginatedResult>;

    /// List timesheet_approval with pagination and filters
    async fn list_with_filters(&self, params: TimesheetApprovalPaginationParams, filters: TimesheetApprovalFilter) -> Result<TimesheetApprovalPaginatedResult>;

    /// Count all timesheet_approval entities
    async fn count(&self) -> Result<u64>;

    /// Count timesheet_approval entities matching filters
    async fn count_with_filters(&self, filters: TimesheetApprovalFilter) -> Result<u64>;

    /// Check if timesheet_approval exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete timesheet_approval by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted timesheet_approval by ID
    async fn restore(&self, id: &str) -> Result<Option<TimesheetApproval>>;

    /// List soft-deleted timesheet_approval entities
    async fn list_deleted(&self, params: TimesheetApprovalPaginationParams) -> Result<TimesheetApprovalPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save timesheet_approval entities
    async fn bulk_save(&self, entities: &[TimesheetApproval]) -> Result<Vec<TimesheetApproval>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
