//! Repository trait for Timesheet aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Timesheet aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Timesheet, TimesheetType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimesheetPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TimesheetPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TimesheetPaginatedResult {
    pub data: Vec<Timesheet>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TimesheetFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub project_id: Option<Uuid>,
    pub task_id: Option<Uuid>,
    pub remark: Option<String>,
    pub entry_type: Option<TimesheetType>,
}

impl TimesheetFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.project_id.is_some() || self.task_id.is_some() || self.remark.is_some() || self.entry_type.is_some()
    }
}

/// Repository trait for Timesheet aggregate
///
/// This trait defines the persistence contract for Timesheet entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TimesheetRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new timesheet entity
    async fn save(&self, entity: &Timesheet) -> Result<Timesheet>;

    /// Find timesheet by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Timesheet>>;

    /// Find all timesheet entities
    async fn find_all(&self) -> Result<Vec<Timesheet>>;

    /// Update timesheet by ID
    async fn update(&self, id: &str, entity: &Timesheet) -> Result<Option<Timesheet>>;

    /// Delete timesheet by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List timesheet with pagination
    async fn list(&self, params: TimesheetPaginationParams) -> Result<TimesheetPaginatedResult>;

    /// List timesheet with pagination and filters
    async fn list_with_filters(&self, params: TimesheetPaginationParams, filters: TimesheetFilter) -> Result<TimesheetPaginatedResult>;

    /// Count all timesheet entities
    async fn count(&self) -> Result<u64>;

    /// Count timesheet entities matching filters
    async fn count_with_filters(&self, filters: TimesheetFilter) -> Result<u64>;

    /// Check if timesheet exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete timesheet by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted timesheet by ID
    async fn restore(&self, id: &str) -> Result<Option<Timesheet>>;

    /// List soft-deleted timesheet entities
    async fn list_deleted(&self, params: TimesheetPaginationParams) -> Result<TimesheetPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save timesheet entities
    async fn bulk_save(&self, entities: &[Timesheet]) -> Result<Vec<Timesheet>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
