//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod timesheet_repository;
mod timesheet_approval_repository;

// Custom persistence modules
// <<< CUSTOM
// Hand-written write SQL for the entry + period-approval flows (user-owned file).
mod timesheet_write_repository;
// END CUSTOM

// Re-exports
pub use timesheet_repository::TimesheetRepository;
pub use timesheet_approval_repository::TimesheetApprovalRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
pub use timesheet_write_repository::{EntryRow, NewEntry, PeriodRow, TimesheetWriteRepository};
// END CUSTOM
