//! Repository for RateCard entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<RateCard, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::RateCard;

/// Table name for RateCard entities
pub const TABLE_NAME: &str = "timesheet.rate_cards";

/// Repository for RateCard entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct RateCardRepository(
    backbone_orm::GenericCrudRepository<RateCard, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for RateCardRepository {
    type Target = backbone_orm::GenericCrudRepository<RateCard, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl RateCardRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(RateCardRepository, RateCard, soft_delete);
