//! Repository for TimesheetApproval entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TimesheetApproval, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::TimesheetApproval;

/// Table name for TimesheetApproval entities
pub const TABLE_NAME: &str = "timesheet.timesheet_approvals";

/// Repository for TimesheetApproval entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TimesheetApprovalRepository(
    backbone_orm::GenericCrudRepository<TimesheetApproval, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TimesheetApprovalRepository {
    type Target = backbone_orm::GenericCrudRepository<TimesheetApproval, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TimesheetApprovalRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TimesheetApprovalRepository, TimesheetApproval, soft_delete);
