//! Validator for RateCard entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<RateCard>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::RateCard;

/// Validator type alias for RateCard entities.
pub type RateCardValidator = EntityValidator<RateCard>;

/// Build a validator for RateCard with all schema-defined field rules.
pub fn rate_card_validator() -> RateCardValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
