//! Validator for TimesheetApproval entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<TimesheetApproval>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::TimesheetApproval;

/// Validator type alias for TimesheetApproval entities.
pub type TimesheetApprovalValidator = EntityValidator<TimesheetApproval>;

/// Build a validator for TimesheetApproval with all schema-defined field rules.
pub fn timesheet_approval_validator() -> TimesheetApprovalValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("remark", |e: &TimesheetApproval| e.remark.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
