//! Validator for Timesheet entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Timesheet>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::Timesheet;

/// Validator type alias for Timesheet entities.
pub type TimesheetValidator = EntityValidator<Timesheet>;

/// Build a validator for Timesheet with all schema-defined field rules.
pub fn timesheet_validator() -> TimesheetValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("remark", |e: &Timesheet| e.remark.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
