//! Auth configuration for TimesheetApproval handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<TimesheetApproval>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TimesheetApprovalService;
use crate::domain::entity::TimesheetApproval;

/// Permission string constants for TimesheetApproval operations.
pub mod permissions {
    pub const LIST:        &str = "timesheet_approval:list";
    pub const READ:        &str = "timesheet_approval:read";
    pub const CREATE:      &str = "timesheet_approval:create";
    pub const UPDATE:      &str = "timesheet_approval:update";
    pub const DELETE:      &str = "timesheet_approval:delete";
    pub const RESTORE:     &str = "timesheet_approval:restore";
    pub const TRASH:       &str = "timesheet_approval:trash";
    pub const EMPTY_TRASH: &str = "timesheet_approval:empty_trash";
    pub const BULK_CREATE: &str = "timesheet_approval:bulk_create";
    pub const UPSERT:      &str = "timesheet_approval:upsert";
}

/// Resource policy for TimesheetApproval — maps CRUD actions to permission strings.
pub struct TimesheetApprovalPolicy;

#[async_trait]
impl ResourcePolicy<TimesheetApproval> for TimesheetApprovalPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &TimesheetApproval,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for TimesheetApproval handlers.
///
/// Wraps `TimesheetApprovalService` and checks `TimesheetApprovalPolicy` before delegating.
pub type TimesheetApprovalGuard = PermissionGuard<TimesheetApproval>;

/// Service-integrated permission guard for TimesheetApproval (for use in generated handlers).
pub type TimesheetApprovalServiceGuard = ServicePermissionGuard<TimesheetApproval, TimesheetApprovalService, TimesheetApprovalPolicy>;

// <<< CUSTOM
// END CUSTOM
