//! Auth configuration for Timesheet handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Timesheet>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TimesheetService;
use crate::domain::entity::Timesheet;

/// Permission string constants for Timesheet operations.
pub mod permissions {
    pub const LIST:        &str = "timesheet:list";
    pub const READ:        &str = "timesheet:read";
    pub const CREATE:      &str = "timesheet:create";
    pub const UPDATE:      &str = "timesheet:update";
    pub const DELETE:      &str = "timesheet:delete";
    pub const RESTORE:     &str = "timesheet:restore";
    pub const TRASH:       &str = "timesheet:trash";
    pub const EMPTY_TRASH: &str = "timesheet:empty_trash";
    pub const BULK_CREATE: &str = "timesheet:bulk_create";
    pub const UPSERT:      &str = "timesheet:upsert";
}

/// Resource policy for Timesheet — maps CRUD actions to permission strings.
pub struct TimesheetPolicy;

#[async_trait]
impl ResourcePolicy<Timesheet> for TimesheetPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Timesheet,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Timesheet handlers.
///
/// Wraps `TimesheetService` and checks `TimesheetPolicy` before delegating.
pub type TimesheetGuard = PermissionGuard<Timesheet>;

/// Service-integrated permission guard for Timesheet (for use in generated handlers).
pub type TimesheetServiceGuard = ServicePermissionGuard<Timesheet, TimesheetService, TimesheetPolicy>;

// <<< CUSTOM
// END CUSTOM
