//! Generic CRUD Test Base
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Provides reusable base for testing all 12 Backbone CRUD endpoints.

use serde_json::{json, Value};
use std::time::Instant;
use uuid::Uuid;

use crate::integration::framework::{ApiTest, TestResult};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CRUD TEST CONFIG
// ============================================================================

/// Configuration for a CRUD test suite
#[derive(Debug, Clone)]
pub struct CrudTestConfig {
    pub base_path: String,
    pub entity_name: String,
    pub supports_soft_delete: bool,
    pub supports_bulk: bool,
}

impl CrudTestConfig {
    pub fn new(base_path: &str, entity_name: &str) -> Self {
        Self {
            base_path: base_path.to_string(),
            entity_name: entity_name.to_string(),
            supports_soft_delete: true,
            supports_bulk: true,
        }
    }
}

// ============================================================================
// TEST DATA GENERATOR
// ============================================================================

/// Trait for entity-specific test data generation
#[allow(async_fn_in_trait)]
pub trait TestDataGenerator: Send + Sync {
    fn generate_create_payload(&self, utils: &CommonUtils) -> Value;
    fn generate_update_payload(&self, id: &str, utils: &CommonUtils) -> Value;
    fn generate_invalid_payload(&self) -> Value;

    /// Extract the created id from the response envelope (`{"data": {"id": ...}}`).
    fn extract_id(&self, response: &Value) -> Option<String> {
        response
            .get("data")
            .and_then(|d| d.get("id"))
            .or_else(|| response.get("id"))
            .and_then(|v| v.as_str())
            .map(String::from)
    }

    /// Seed required foreign-key parents; returns (payload_field, parent_id) overrides.
    /// Default: none. Overridden for entities with required intra-module FKs.
    async fn seed_dependencies(&self, _api: &ApiTest) -> Vec<(String, String)> {
        Vec::new()
    }
}

/// Create an entity (seeding its own required FK parents first) and return its id.
pub async fn create_and_get_id<G: TestDataGenerator>(
    api: &ApiTest,
    base_path: &str,
    generator: &G,
) -> Option<String> {
    let utils = CommonUtils::default();
    let mut payload = generator.generate_create_payload(&utils);
    for (field, id) in generator.seed_dependencies(api).await {
        payload[field.as_str()] = json!(id);
    }
    let response = api.post(base_path, &payload, None).await.ok()?;
    let body = response.json_value().ok()?;
    body.get("data").and_then(|d| d.get("id")).or_else(|| body.get("id")).and_then(|v| v.as_str()).map(String::from)
}

// ============================================================================
// GENERIC CRUD TEST
// ============================================================================

/// Generic CRUD Test Suite
pub struct GenericCrudTest<G: TestDataGenerator> {
    pub config: CrudTestConfig,
    pub api_test: ApiTest,
    pub utils: CommonUtils,
    pub generator: G,
    pub created_ids: Vec<String>,
}

impl<G: TestDataGenerator> GenericCrudTest<G> {
    pub fn new(config: CrudTestConfig, generator: G) -> Self {
        let api_base_url = std::env::var("API_BASE_URL")
            .unwrap_or_else(|_| "http://127.0.0.1:3000".to_string());

        Self {
            api_test: ApiTest::new(&config.entity_name, &api_base_url),
            config,
            utils: CommonUtils::default(),
            generator,
            created_ids: Vec::new(),
        }
    }

    fn endpoint(&self, suffix: &str) -> String {
        format!("{}{}", self.config.base_path, suffix)
    }

    /// Check if the API server is reachable and routes are registered
    /// Returns (server_reachable, routes_registered)
    async fn check_server_status(&self) -> (bool, bool) {
        match self.api_test.get(&self.endpoint(""), None).await {
            Ok(response) => {
                // Server responded
                let server_reachable = true;
                // 404 means routes not registered, 2xx/4xx/5xx means routes exist
                let routes_registered = response.status_code != 404;
                (server_reachable, routes_registered)
            }
            Err(_) => {
                // Connection failed - server not running
                (false, false)
            }
        }
    }

    /// Create a skipped result for when server isn't available
    fn skipped_result(&self, test_name: &str, reason: &str) -> TestResult {
        TestResult::success(test_name, &format!("SKIPPED: {}", reason))
    }

    /// Test: List entities (GET /collection)
    pub async fn test_list(&self) -> TestResult {
        let test_name = format!("{} - List", self.config.entity_name);
        let start = Instant::now();

        match self.api_test.get(&self.endpoint(""), None).await {
            Ok(response) => self.api_test.create_result(
                &test_name,
                &response,
                200,
                "List endpoint works",
            ),
            Err(e) => TestResult::failure(&test_name, e.to_string()),
        }
    }

    /// Test: Create entity (POST /collection)
    pub async fn test_create(&mut self) -> TestResult {
        let test_name = format!("{} - Create", self.config.entity_name);
        let mut payload = self.generator.generate_create_payload(&self.utils);
        for (field, id) in self.generator.seed_dependencies(&self.api_test).await {
            payload[field.as_str()] = json!(id);
        }

        match self.api_test.post(&self.endpoint(""), &payload, None).await {
            Ok(response) => {
                if response.is_success() {
                    if let Ok(json) = response.json_value() {
                        if let Some(id) = self.generator.extract_id(&json) {
                            self.created_ids.push(id);
                        }
                    }
                }
                self.api_test.create_result(&test_name, &response, 201, "Create works")
            }
            Err(e) => TestResult::failure(&test_name, e.to_string()),
        }
    }

    /// Test: Get entity by ID (GET /collection/:id)
    pub async fn test_get_by_id(&self, id: &str) -> TestResult {
        let test_name = format!("{} - Get by ID", self.config.entity_name);

        match self.api_test.get(&self.endpoint(&format!("/{}", id)), None).await {
            Ok(response) => self.api_test.create_result(&test_name, &response, 200, "Get by ID works"),
            Err(e) => TestResult::failure(&test_name, e.to_string()),
        }
    }

    /// Test: Update entity (PUT /collection/:id)
    pub async fn test_update(&self, id: &str) -> TestResult {
        let test_name = format!("{} - Update", self.config.entity_name);
        let mut payload = self.generator.generate_update_payload(id, &self.utils);
        for (field, pid) in self.generator.seed_dependencies(&self.api_test).await {
            payload[field.as_str()] = json!(pid);
        }

        match self.api_test.put(&self.endpoint(&format!("/{}", id)), &payload, None).await {
            Ok(response) => self.api_test.create_result(&test_name, &response, 200, "Update works"),
            Err(e) => TestResult::failure(&test_name, e.to_string()),
        }
    }

    /// Test: Delete entity (DELETE /collection/:id)
    pub async fn test_delete(&self, id: &str) -> TestResult {
        let test_name = format!("{} - Delete", self.config.entity_name);

        match self.api_test.delete(&self.endpoint(&format!("/{}", id)), None).await {
            Ok(response) => self.api_test.create_result(&test_name, &response, 200, "Delete works"),
            Err(e) => TestResult::failure(&test_name, e.to_string()),
        }
    }

    /// Test: Invalid create (POST with bad data)
    pub async fn test_invalid_create(&self) -> TestResult {
        let test_name = format!("{} - Invalid Create", self.config.entity_name);
        let payload = self.generator.generate_invalid_payload();

        match self.api_test.post(&self.endpoint(""), &payload, None).await {
            Ok(response) => {
                if response.status_code >= 400 {
                    TestResult::success(&test_name, "Validation rejects invalid data")
                } else {
                    TestResult::failure(&test_name, "Should reject invalid data")
                }
            }
            Err(e) => TestResult::failure(&test_name, e.to_string()),
        }
    }

    /// Test: Not found (GET with invalid ID)
    pub async fn test_not_found(&self) -> TestResult {
        let test_name = format!("{} - Not Found", self.config.entity_name);
        let fake_id = Uuid::new_v4().to_string();

        match self.api_test.get(&self.endpoint(&format!("/{}", fake_id)), None).await {
            Ok(response) => self.api_test.create_result(&test_name, &response, 404, "Returns 404 for missing"),
            Err(e) => TestResult::failure(&test_name, e.to_string()),
        }
    }

    /// Test: Bulk soft-delete (POST /collection/delete/bulk)
    pub async fn test_bulk_delete(&self, ids: &[String]) -> TestResult {
        let test_name = format!("{} - Bulk Delete", self.config.entity_name);
        let payload = serde_json::json!({ "ids": ids });
        match self.api_test.post(&self.endpoint("/delete/bulk"), &payload, None).await {
            Ok(response) => self.api_test.create_result(&test_name, &response, 200, "Bulk soft-delete works"),
            Err(e) => TestResult::failure(&test_name, e.to_string()),
        }
    }

    /// Test: Bulk restore (POST /collection/restore/bulk)
    pub async fn test_bulk_restore(&self, ids: &[String]) -> TestResult {
        let test_name = format!("{} - Bulk Restore", self.config.entity_name);
        let payload = serde_json::json!({ "ids": ids });
        match self.api_test.post(&self.endpoint("/restore/bulk"), &payload, None).await {
            Ok(response) => self.api_test.create_result(&test_name, &response, 200, "Bulk restore works"),
            Err(e) => TestResult::failure(&test_name, e.to_string()),
        }
    }

    /// Test: Restore all soft-deleted (POST /collection/restore/all)
    pub async fn test_restore_all(&self) -> TestResult {
        let test_name = format!("{} - Restore All", self.config.entity_name);
        let payload = serde_json::json!({});
        match self.api_test.post(&self.endpoint("/restore/all"), &payload, None).await {
            Ok(response) => self.api_test.create_result(&test_name, &response, 200, "Restore all works"),
            Err(e) => TestResult::failure(&test_name, e.to_string()),
        }
    }

    /// Run all CRUD tests
    pub async fn run_all(&mut self) -> Vec<TestResult> {
        let mut results = Vec::new();

        // Check if server is reachable and routes are registered
        let (server_reachable, routes_registered) = self.check_server_status().await;

        if !server_reachable {
            let skip_reason = "API server not reachable. Set API_BASE_URL and ensure server is running.";
            results.push(self.skipped_result(&format!("{} - List", self.config.entity_name), skip_reason));
            results.push(self.skipped_result(&format!("{} - Create", self.config.entity_name), skip_reason));
            results.push(self.skipped_result(&format!("{} - Invalid Create", self.config.entity_name), skip_reason));
            results.push(self.skipped_result(&format!("{} - Not Found", self.config.entity_name), skip_reason));
            return results;
        }

        if !routes_registered {
            let skip_reason = "Routes not registered. Module may not be integrated in the app yet.";
            results.push(self.skipped_result(&format!("{} - List", self.config.entity_name), skip_reason));
            results.push(self.skipped_result(&format!("{} - Create", self.config.entity_name), skip_reason));
            results.push(self.skipped_result(&format!("{} - Invalid Create", self.config.entity_name), skip_reason));
            results.push(self.skipped_result(&format!("{} - Not Found", self.config.entity_name), skip_reason));
            return results;
        }

        // List
        results.push(self.test_list().await);

        // Create
        results.push(self.test_create().await);

        // Get by ID (using created entity)
        if let Some(id) = self.created_ids.last() {
            results.push(self.test_get_by_id(id).await);
            results.push(self.test_update(id).await);
        }

        // Validation tests
        results.push(self.test_invalid_create().await);
        results.push(self.test_not_found().await);

        // Batch soft-delete ops — only for entities that support soft-delete.
        // (No-soft-delete entities hard-delete here, which would 404 the cleanup below.)
        let batch_ids: Vec<String> = self.created_ids.clone();
        if self.config.supports_soft_delete && !batch_ids.is_empty() {
            results.push(self.test_bulk_delete(&batch_ids).await);
            results.push(self.test_bulk_restore(&batch_ids).await);
            results.push(self.test_restore_all().await);
        }

        // Cleanup - delete created entities
        for id in self.created_ids.clone() {
            results.push(self.test_delete(&id).await);
        }

        results
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add custom test utilities here
// <<< CUSTOM TESTS END >>>
