//! RateCard API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the RateCard CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// RATECARD TEST DATA GENERATOR
// ============================================================================

/// Test data generator for RateCard
pub struct RateCardTestData;

impl TestDataGenerator for RateCardTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        json!({
            "id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "activity_type_id": null,
            "billing_rate": null,
            "costing_rate": null,
            "valid_from": Utc::now().format("%Y-%m-%d").to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        json!({
            "id": id,
            "employee_id": Uuid::new_v4().to_string(),
            "activity_type_id": null,
            "billing_rate": null,
            "costing_rate": null,
            "valid_from": Utc::now().format("%Y-%m-%d").to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// RATECARD API TEST
// ============================================================================

/// RateCard API test suite
pub struct RateCardApiTest {
    inner: GenericCrudTest<RateCardTestData>,
}

impl RateCardApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/rate_cards", "RateCard");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, RateCardTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for RateCardApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_rate_card_crud() {
        let mut test = RateCardApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add RateCard specific tests here
// <<< CUSTOM TESTS END >>>
