//! TimesheetApproval API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the TimesheetApproval CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// TIMESHEETAPPROVAL TEST DATA GENERATOR
// ============================================================================

/// Test data generator for TimesheetApproval
pub struct TimesheetApprovalTestData;

impl TestDataGenerator for TimesheetApprovalTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "approver_id": null,
            "year": 1,
            "month": 1,
            "remark": null,
            "billable_time": null,
            "billable_cost": null,
            "status": "pending",
            "approval_request_id": null,
            "submitted_at": now,
            "data": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "approver_id": null,
            "year": 1,
            "month": 1,
            "remark": null,
            "billable_time": null,
            "billable_cost": null,
            "status": "pending",
            "approval_request_id": null,
            "submitted_at": now,
            "data": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// TIMESHEETAPPROVAL API TEST
// ============================================================================

/// TimesheetApproval API test suite
pub struct TimesheetApprovalApiTest {
    inner: GenericCrudTest<TimesheetApprovalTestData>,
}

impl TimesheetApprovalApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/timesheet_approvals", "TimesheetApproval");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, TimesheetApprovalTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for TimesheetApprovalApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_timesheet_approval_crud() {
        let mut test = TimesheetApprovalApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add TimesheetApproval specific tests here
// <<< CUSTOM TESTS END >>>
