//! Timesheet API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Timesheet CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// TIMESHEET TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Timesheet
pub struct TimesheetTestData;

impl TestDataGenerator for TimesheetTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "project_id": null,
            "task_id": null,
            "year": 1,
            "month": 1,
            "date": Utc::now().format("%Y-%m-%d").to_string(),
            "remark": null,
            "time_start": null,
            "time_end": null,
            "entry_type": "work",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "project_id": null,
            "task_id": null,
            "year": 1,
            "month": 1,
            "date": Utc::now().format("%Y-%m-%d").to_string(),
            "remark": null,
            "time_start": null,
            "time_end": null,
            "entry_type": "work",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// TIMESHEET API TEST
// ============================================================================

/// Timesheet API test suite
pub struct TimesheetApiTest {
    inner: GenericCrudTest<TimesheetTestData>,
}

impl TimesheetApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/timesheets", "Timesheet");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, TimesheetTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for TimesheetApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_timesheet_crud() {
        let mut test = TimesheetApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Timesheet specific tests here
// <<< CUSTOM TESTS END >>>
