//! Timesheet Custom Handlers
//!
//! Generated by metaphor-schema. Safe to edit.
//!
//! Add custom HTTP handlers here that need access to AppState.
//! These handlers can be integrated with the routes module.

#![allow(unused_imports)]

use axum::{
    extract::{State, Path, Query, Json},
    response::IntoResponse,
    http::StatusCode,
};
use serde::{Deserialize, Serialize};

use super::AppState;

// ============================================================
// CUSTOM HANDLERS
// ============================================================

// <<< CUSTOM HANDLERS START >>>

/// Example custom handler demonstrating AppState usage.
///
/// # Example
///
/// ```ignore
/// // In routes/mod.rs:
/// Router::new().route("/health", get(health_check))
/// ```
#[allow(dead_code)]
pub async fn health_check(
    State(_state): State<AppState>,
) -> impl IntoResponse {
    // Access services via _state if needed
    // e.g., _state.user_service.health_check().await
    (StatusCode::OK, "OK")
}

// Add more custom handlers below...

// <<< CUSTOM HANDLERS END >>>