//! Timesheet Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::TimesheetService;
use crate::application::service::TimesheetApprovalService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Timesheet service
    pub timesheet_service: Arc<TimesheetService>,
    /// TimesheetApproval service
    pub timesheet_approval_service: Arc<TimesheetApprovalService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        timesheet_service: Arc<TimesheetService>,
        timesheet_approval_service: Arc<TimesheetApprovalService>
    ) -> Self {
        Self {
            timesheet_service,
            timesheet_approval_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::TimesheetModule) -> Self {
        Self {
            timesheet_service: module.timesheet_service.clone(),
            timesheet_approval_service: module.timesheet_approval_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    timesheet_service: Option<Arc<TimesheetService>>,
    timesheet_approval_service: Option<Arc<TimesheetApprovalService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Timesheet service.
    pub fn with_timesheet_service(mut self, service: Arc<TimesheetService>) -> Self {
        self.timesheet_service = Some(service);
        self
    }

    /// Set the TimesheetApproval service.
    pub fn with_timesheet_approval_service(mut self, service: Arc<TimesheetApprovalService>) -> Self {
        self.timesheet_approval_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            timesheet_service: self.timesheet_service.expect("timesheet_service is required"),
            timesheet_approval_service: self.timesheet_approval_service.expect("timesheet_approval_service is required"),
        }
    }
}
