//! Data Transfer Objects
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.
//!
//! Entity DTOs for this module live in `crate::presentation::dto`. This module
//! is reserved for any future cross-cutting DTOs.
