//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    timesheet_handler::create_timesheet_routes,
    timesheet_approval_handler::create_timesheet_approval_routes,
};

use crate::application::service::{
    TimesheetService,
    TimesheetApprovalService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub timesheet: Arc<TimesheetService>,
    pub timesheet_approval: Arc<TimesheetApprovalService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Timesheet routes (12 Backbone endpoints)
        .merge(create_timesheet_routes(services.timesheet))
        // TimesheetApproval routes (12 Backbone endpoints)
        .merge(create_timesheet_approval_routes(services.timesheet_approval))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn timesheet_routes(service: Arc<TimesheetService>) -> Router {
        create_timesheet_routes(service)
    }

    pub fn timesheet_approval_routes(service: Arc<TimesheetApprovalService>) -> Router {
        create_timesheet_approval_routes(service)
    }

}
