//! Public events for Timesheet module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// TIMESHEET EVENTS
// ============================================================================

/// Event published when a Timesheet is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetCreatedEvent {
    pub id: TimesheetId,
    pub data: TimesheetDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Timesheet is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetUpdatedEvent {
    pub id: TimesheetId,
    pub data: TimesheetDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Timesheet is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetDeletedEvent {
    pub id: TimesheetId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// TIMESHEETAPPROVAL EVENTS
// ============================================================================

/// Event published when a TimesheetApproval is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetApprovalCreatedEvent {
    pub id: TimesheetApprovalId,
    pub data: TimesheetApprovalDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TimesheetApproval is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetApprovalUpdatedEvent {
    pub id: TimesheetApprovalId,
    pub data: TimesheetApprovalDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TimesheetApproval is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetApprovalDeletedEvent {
    pub id: TimesheetApprovalId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Timesheet module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum TimesheetEvent {
    TimesheetCreated(TimesheetCreatedEvent),
    TimesheetUpdated(TimesheetUpdatedEvent),
    TimesheetDeleted(TimesheetDeletedEvent),
    TimesheetApprovalCreated(TimesheetApprovalCreatedEvent),
    TimesheetApprovalUpdated(TimesheetApprovalUpdatedEvent),
    TimesheetApprovalDeleted(TimesheetApprovalDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimesheetEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for TimesheetEventMetadata {
    fn default() -> Self {
        Self {
            module: "timesheet",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
