//! Timesheet Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Timesheet exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use timesheet::exports::{RateCardDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `RateCardDto` - Data transfer object for RateCard
/// - `RateCardSummary` - Summary view of RateCard
/// - `RateCardId` - Type-safe ID wrapper
/// - `TimesheetDto` - Data transfer object for Timesheet
/// - `TimesheetSummary` - Summary view of Timesheet
/// - `TimesheetId` - Type-safe ID wrapper
/// - `TimesheetApprovalDto` - Data transfer object for TimesheetApproval
/// - `TimesheetApprovalSummary` - Summary view of TimesheetApproval
/// - `TimesheetApprovalId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `RateCardCreatedEvent` - Published when RateCard is created
/// - `RateCardUpdatedEvent` - Published when RateCard is updated
/// - `RateCardDeletedEvent` - Published when RateCard is deleted
/// - `TimesheetCreatedEvent` - Published when Timesheet is created
/// - `TimesheetUpdatedEvent` - Published when Timesheet is updated
/// - `TimesheetDeletedEvent` - Published when Timesheet is deleted
/// - `TimesheetApprovalCreatedEvent` - Published when TimesheetApproval is created
/// - `TimesheetApprovalUpdatedEvent` - Published when TimesheetApproval is updated
/// - `TimesheetApprovalDeletedEvent` - Published when TimesheetApproval is deleted
pub struct ExportSummary;
