//! Public services for Timesheet module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Timesheet module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait TimesheetQueryService: Send + Sync {
    /// Get Timesheet by ID
    async fn get_timesheet(&self, id: TimesheetId) -> Result<Option<TimesheetDto>>;

    /// Get Timesheet summary by ID
    async fn get_timesheet_summary(&self, id: TimesheetId) -> Result<Option<TimesheetSummary>>;

    /// Check if Timesheet exists
    async fn timesheet_exists(&self, id: TimesheetId) -> Result<bool>;

    /// Get TimesheetApproval by ID
    async fn get_timesheet_approval(&self, id: TimesheetApprovalId) -> Result<Option<TimesheetApprovalDto>>;

    /// Get TimesheetApproval summary by ID
    async fn get_timesheet_approval_summary(&self, id: TimesheetApprovalId) -> Result<Option<TimesheetApprovalSummary>>;

    /// Check if TimesheetApproval exists
    async fn timesheet_approval_exists(&self, id: TimesheetApprovalId) -> Result<bool>;

}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
