//! Timesheet Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::TimesheetService;
pub use application::service::TimesheetApprovalService;

// Re-exports - Workflows
pub use application::workflows::*;

// <<< CUSTOM
// The validated write path (entries under the period lock, submit window, period transitions,
// approvals seam — H-6) and its guarded HTTP composition, plus `company_scope` re-exported for
// the RLS probe suite (tests/ can only see the public surface, mirroring backbone-party).
pub use application::service::{
    last_day_of_month, TimesheetEntryDto, TimesheetError, TimesheetWriteService,
    TimesheetFiling, TimesheetFilingRequest, TimesheetSeamError, TimesheetVerdict,
    UnwiredTimesheetApprovals,
};
pub use presentation::http::create_guarded_timesheet_routes;
pub use backbone_orm::company_scope;
// END CUSTOM

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Timesheet module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let timesheet = TimesheetModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = timesheet.all_crud_routes();
/// ```
pub struct TimesheetModule {
    pub(crate) timesheet_service: Arc<TimesheetService>,
    pub(crate) timesheet_approval_service: Arc<TimesheetApprovalService>,
    // <<< CUSTOM FIELDS
    /// Validated entry + period writes (period lock, submit window, overlap mapping, approvals
    /// seam). The guarded routes compose off this; `set_approvals` wires the engine port.
    pub timesheet_write_service: Arc<TimesheetWriteService>,
    // END CUSTOM
}

impl TimesheetModule {
    /// Create a new module builder
    pub fn builder() -> TimesheetModuleBuilder {
        TimesheetModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_timesheet_routes,
            create_timesheet_approval_routes,
        };

        Router::new()
            .merge(create_timesheet_routes(self.timesheet_service.clone()))
            .merge(create_timesheet_approval_routes(self.timesheet_approval_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_timesheet_read_routes,
            create_timesheet_approval_read_routes,
        };

        Router::new()
            .merge(create_timesheet_read_routes(self.timesheet_service.clone()))
            .merge(create_timesheet_approval_read_routes(self.timesheet_approval_service.clone()))
    }

    // <<< CUSTOM METHODS
    // END CUSTOM
}

/// Builder for TimesheetModule
pub struct TimesheetModuleBuilder {
    db_pool: Option<PgPool>,
}

impl TimesheetModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<TimesheetModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Timesheet service
        let timesheet_repository = Arc::new(TimesheetRepository::new(db_pool.clone()));
        let timesheet_service = Arc::new(TimesheetService::with_repository(timesheet_repository.clone()));

        // TimesheetApproval service
        let timesheet_approval_repository = Arc::new(TimesheetApprovalRepository::new(db_pool.clone()));
        let timesheet_approval_service = Arc::new(TimesheetApprovalService::with_repository(timesheet_approval_repository.clone()));

        // <<< CUSTOM
        let timesheet_write_service = Arc::new(TimesheetWriteService::new(db_pool.clone()));
        // END CUSTOM

        Ok(TimesheetModule {
            timesheet_service,
            timesheet_approval_service,
            // <<< CUSTOM
            timesheet_write_service,
            // END CUSTOM
        })
    }
}

impl Default for TimesheetModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
