//! Use case base traits — re-exported from backbone-core.
//!
//! Generated by metaphor-schema. Do not edit manually.

pub use backbone_core::{
    UseCaseError, UseCaseResult,
    UseCaseHooks, DefaultHooks,
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};
