//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod timesheet_usecases;
pub mod timesheet_approval_usecases;

pub use timesheet_usecases::{
    CreateTimesheetUseCase, UpdateTimesheetUseCase, GetTimesheetUseCase,
    DeleteTimesheetUseCase, ListTimesheetUseCase,
};
pub use timesheet_approval_usecases::{
    CreateTimesheetApprovalUseCase, UpdateTimesheetApprovalUseCase, GetTimesheetApprovalUseCase,
    DeleteTimesheetApprovalUseCase, ListTimesheetApprovalUseCase,
};

// <<< CUSTOM
// END CUSTOM
