//! Use case type aliases for Timesheet aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTimesheetDto, UpdateTimesheetDto};
use crate::application::service::TimesheetService;
use crate::domain::entity::Timesheet;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTimesheetUseCase = CreateUseCase<Timesheet, CreateTimesheetDto, TimesheetService>;
pub type UpdateTimesheetUseCase = UpdateUseCase<Timesheet, UpdateTimesheetDto, TimesheetService>;
pub type GetTimesheetUseCase    = GetUseCase<Timesheet, TimesheetService>;
pub type DeleteTimesheetUseCase = DeleteUseCase<Timesheet, TimesheetService>;
pub type ListTimesheetUseCase   = ListUseCase<Timesheet, TimesheetService>;

// <<< CUSTOM
// END CUSTOM
