//! Use case type aliases for TimesheetApproval aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTimesheetApprovalDto, UpdateTimesheetApprovalDto};
use crate::application::service::TimesheetApprovalService;
use crate::domain::entity::TimesheetApproval;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTimesheetApprovalUseCase = CreateUseCase<TimesheetApproval, CreateTimesheetApprovalDto, TimesheetApprovalService>;
pub type UpdateTimesheetApprovalUseCase = UpdateUseCase<TimesheetApproval, UpdateTimesheetApprovalDto, TimesheetApprovalService>;
pub type GetTimesheetApprovalUseCase    = GetUseCase<TimesheetApproval, TimesheetApprovalService>;
pub type DeleteTimesheetApprovalUseCase = DeleteUseCase<TimesheetApproval, TimesheetApprovalService>;
pub type ListTimesheetApprovalUseCase   = ListUseCase<TimesheetApproval, TimesheetApprovalService>;

// <<< CUSTOM
// END CUSTOM
